complexity:
  LongMethod:
    excludes:
      - '**/DesignReviewApp.kt'
  TooManyFunctions:
    ignoreAnnotatedFunctions:
      - Composable

naming:
  FunctionNaming:
    excludeClassPattern: '.*Test'
    excludes:
      - '**/DesignReviewApp.kt'
      - '**/Main.kt'
      - '**/ProductSurface.kt'
      - '**/ReadyContent.kt'
